### PR TITLE
Adding govet to travis yml

### PR DESCRIPTION
**Pull request by fntlnz**
When travis will run it you will know why I added it

testing1

### CODE REVIEW

**Comment by fntlnz** [comment]
Printf with dollars! YOU KNOW

**Comment by fntlnz** [comment]
https://github.com/gianarb/steady/blob/master/proxy/dispatch.go#L35-L35

**Comment by gianarb** [comment]
don't stop me now!

**Comment by fntlnz** [comment]
@gianarb you deserve it

**Comment by gianarb** [comment]
Thanks

**Pull request merged**
